//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// Copyright (c) Matthieu MEZIL.  All rights reserved.
// matthieu.mezil@live.fr

 
using System;
using System.Linq;
using System.Linq.Expressions;
using WebApplication1;

namespace WebApplication1.DAL.Interfaces
{
    public interface IEntity1DALSpecifications 
    {
        Expression<Func<WebApplication1.Entity1, int>> NameLengthExpression { get; }
    }
}
