//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// Copyright (c) Matthieu MEZIL.  All rights reserved.
// matthieu.mezil@live.fr

 
using System;
using System.Collections.Generic;
using WCFAsyncQueryableServices.DAL.Interfaces;
using WCFAsyncQueryableServices.SerializableExpressions;
using WCFAsyncQueryableServices.Service.Interfaces;
using WebApplication1;

namespace WebApplication1.Service.Interfaces
{
    public partial interface IWAQSModelService : WCFAsyncQueryableServices.Service.Interfaces.IService, IDisposable
    {	
    	IEntitySet<WebApplication1.Entity1> Entity1 { get; }
    	void ApplyChanges(WebApplication1.Entity1 entity);
     
    	WAQSModelQueryResult Execute(QuerySerialization query);
    
    	WAQSModelQueriesResult ExecuteMany(QueriesSerialization queries);
    
    	WAQSModelQueryResultPage LoadPage(int pageSize, SerializableExpression queryExpression, IEnumerable<string> withSpecificationsProperties, LoadPageParameter[] identifiers);
    
    	DateTime GetDbDateTime();
    	
    	void SaveChanges();
    
    	IEnumerable<Error> Validate(Entity1 entity);
    }
}
