//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// Copyright (c) Matthieu MEZIL.  All rights reserved.
// matthieu.mezil@live.fr

 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using WCFAsyncQueryableServices.DAL.Interfaces;
using WCFAsyncQueryableServices.DAL.Interfaces.L2E;

namespace WebApplication1.DAL.Interfaces
{
    public partial interface IWAQSModelContainer : IObjectContext, IDisposable
    {
        #region EntitySet Properties
    
        IEntitySet<WebApplication1.Entity1> Entity1 { get; }
        Expression<Func<IQueryable<WebApplication1.Entity1>>> Entity1Expression { get; }

        #endregion

     
        #region Specifications
        IEntity1DALSpecifications Entity1DALSpecifications { get; }

        #endregion

    }
}
