//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// Copyright (c) Matthieu MEZIL.  All rights reserved.
// matthieu.mezil@live.fr

 
using System;
using System.Collections.Generic;
using System.ServiceModel;
using WCFAsyncQueryableServices.SerializableExpressions;
using WCFAsyncQueryableServices.Service.Interfaces;
using WCFAsyncQueryableServices.WCFService.Contract;
using WebApplication1;
using WebApplication1.Service.Interfaces;

namespace WebApplication1.WCFService.Contract
{
    [ServiceContract(Namespace="http://WAQSModel.net", Name="IWAQSModelService")]
    [WAQSModelFaults]
    public partial interface IWAQSModelWCFService
    {	
    	[OperationContract]
    	WAQSModelQueryResult Execute(QuerySerialization query);
    
    	[OperationContract]
    	WAQSModelQueriesResult ExecuteMany(QueriesSerialization queries);
    
    	[OperationContract]
    	WAQSModelQueryResultPage LoadPage(int pageSize, SerializableExpression queryExpression, string[] withSpecificationsProperties, LoadPageParameter[] identifiers);
    
    	[OperationContract]
    	DateTime GetDbDateTime();
    	
    	[OperationContract]
    	WAQSModelSerializableContext SaveChanges(WAQSModelSerializableContext context);
    
    	[OperationContract(Name="ValidateEntity1")]
    	List<Error> Validate(Entity1 entity);
    }
}
