//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// Copyright (c) Matthieu MEZIL.  All rights reserved.
// matthieu.mezil@live.fr

 
using System;

namespace WCFAsyncQueryableServices.DAL
{
    public static class MergeOptionExtensions
    {
        public static System.Data.Entity.Core.Objects.MergeOption ToEFMergeOption(this WCFAsyncQueryableServices.DAL.Interfaces.MergeOption mergOption)
        {
            switch (mergOption)
            {
                case WCFAsyncQueryableServices.DAL.Interfaces.MergeOption.AppendOnly:
                    return System.Data.Entity.Core.Objects.MergeOption.AppendOnly;
                case WCFAsyncQueryableServices.DAL.Interfaces.MergeOption.OverwriteChanges:
                    return System.Data.Entity.Core.Objects.MergeOption.OverwriteChanges;
                case WCFAsyncQueryableServices.DAL.Interfaces.MergeOption.PreserveChanges:
                    return System.Data.Entity.Core.Objects.MergeOption.PreserveChanges;
                case WCFAsyncQueryableServices.DAL.Interfaces.MergeOption.NoTracking:
                    return System.Data.Entity.Core.Objects.MergeOption.NoTracking;
                default:
                    throw new NotImplementedException();
            }  
        }
    }
}
