//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// Copyright (c) Matthieu MEZIL.  All rights reserved.
// matthieu.mezil@live.fr

 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;
using WCFAsyncQueryableServices.DAL.Interfaces;
using WebApplication1.DAL.Interfaces;

namespace WebApplication1.Service
{
    public static partial class WAQSModelQueryableExtension
    {
        public static IWAQSQuery<WebApplication1.Entity1> WithNameLength(this IWAQSQuery<WebApplication1.Entity1> source)
        {
            return WCFAsyncQueryableServices.DAL.Interfaces.QueryableExtensions.CreateWAQSQuery<WebApplication1.Entity1>(source, source.QueryableIncludes, source.WithSpecifications == null ? new string[] {"NameLength"} : source.WithSpecifications.Union(new string[] {"NameLength"}));
        }	
    
        public static IWAQSQueryValue<WebApplication1.Entity1> WithNameLength(this IWAQSQueryValue<WebApplication1.Entity1> source)
        {
            return WCFAsyncQueryableServices.DAL.Interfaces.QueryableExtensions.CreateWAQSQueryValue<WebApplication1.Entity1>(source, source.QueryableIncludes, source.WithSpecifications == null ? new string[] {"NameLength"} : source.WithSpecifications.Union(new string[] {"NameLength"}));
        }	
    
        [IncludeMethod]
        public static IEnumerable<WebApplication1.Entity1> WithNameLength(this IEnumerable<WebApplication1.Entity1> source)
        {
            return source;
        }	
    
        [IncludeMethod]
        public static WebApplication1.Entity1 WithNameLength(this WebApplication1.Entity1 source)
        {
            return source;
        }	
    
            [IncludeMethod]
            public static IWAQSQuery<WebApplication1.Entity1> IncludeForNameLength(this IWAQSQuery<WebApplication1.Entity1> query)
            {
                bool done = false;
                IncludeForNameLengthCustomQueryable(ref query, ref done);
                return query;
            }
            static partial void IncludeForNameLengthCustomQueryable(ref IWAQSQuery<WebApplication1.Entity1> query, ref bool done);
    
            [IncludeMethod]
            public static IEnumerable<WebApplication1.Entity1> IncludeForNameLength(this IEnumerable<WebApplication1.Entity1> source)
            {
                return source;
            }
    
            [IncludeMethod]
            public static IWAQSQueryValue<WebApplication1.Entity1> IncludeForNameLength(this IWAQSQueryValue<WebApplication1.Entity1> query)
            {
                bool done = false;
                IncludeForNameLengthCustomIWAQSQueryValue(ref query, ref done);
                return query;
            }
            static partial void IncludeForNameLengthCustomIWAQSQueryValue(ref IWAQSQueryValue<WebApplication1.Entity1> query, ref bool done);
    
            [IncludeMethod]
            public static WebApplication1.Entity1 IncludeForNameLength(this WebApplication1.Entity1 source)
            {
                return source;
            }
    
    }
}
