//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// Copyright (c) Matthieu MEZIL.  All rights reserved.
// matthieu.mezil@live.fr

 
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Core.Metadata.Edm;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Core.Objects.DataClasses;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using System.Text;
using System.Text.RegularExpressions;
using WCFAsyncQueryableServices.Common;
using WCFAsyncQueryableServices.Specifications;
using WCFAsyncQueryableServices.DAL;
using WCFAsyncQueryableServices.Entities;
using WebApplication1.DAL.Interfaces;
using WCFAsyncQueryableServices.DAL.Interfaces;
using WCFAsyncQueryableServices.DAL.Interfaces.L2E;
using System.Threading.Tasks;

namespace WebApplication1.DAL
{
    public partial class WAQSModelContainer : CustomizableObjectContext, IWAQSModelContainer
    {
        public const string ConnectionString = "name=WAQSModelContainer";
        public const string ContainerName = "WAQSModelContainer";
    
        #region Constructors
    
        public WAQSModelContainer()
            : base(ConnectionString, ContainerName)
        {
            Initialize();
        }
    
        private void Initialize()
        {
            ContextOptions.ProxyCreationEnabled = false;
            ObjectMaterialized += new ObjectMaterializedEventHandler(HandleObjectMaterialized);
            OnInitialize();
        }
        partial void OnInitialize();
    
        private void HandleObjectMaterialized(object sender, ObjectMaterializedEventArgs e)
        {
            var entity = e.Entity as WCFAsyncQueryableServices.Entities.IObjectWithChangeTracker;
            if (entity != null)
            {
                bool changeTrackingEnabled = entity.ChangeTracker.ChangeTrackingEnabled;
                try
                {
                    entity.MarkAsUnchanged();
                }
                finally
                {
                    entity.ChangeTracker.ChangeTrackingEnabled = changeTrackingEnabled;
                }
                this.StoreReferenceKeyValues(entity);
            }
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<WebApplication1.Entity1> Entity1
        {
            get { return _entity1  ?? (_entity1 = CreateObjectSet<WebApplication1.Entity1>("Entity1")); }
        }
        private ObjectSet<WebApplication1.Entity1> _entity1;
        IEntitySet<WebApplication1.Entity1> IWAQSModelContainer.Entity1
        {
            get { return _entity1EntitySet ?? (_entity1EntitySet = new EntitySet<WebApplication1.Entity1>(Entity1, TransformExpression));}
        }
        private EntitySet<WebApplication1.Entity1> _entity1EntitySet;
        Expression<Func<IQueryable<WebApplication1.Entity1>>> IWAQSModelContainer.Entity1Expression
        {
            get
            {
                var context = this;
                context.Entity1.MergeOption = EFMergeOption;
                return () => context.Entity1;
            }
        }

        #endregion

    
        private WCFAsyncQueryableServices.DAL.Interfaces.MergeOption _defaultMergeOption = WCFAsyncQueryableServices.DAL.Interfaces.MergeOption.NoTracking;
        public WCFAsyncQueryableServices.DAL.Interfaces.MergeOption DefaultMergeOption
        {
            get { return _defaultMergeOption; }
            set { _defaultMergeOption = value; }
        }
        private System.Data.Entity.Core.Objects.MergeOption EFMergeOption
        {
            get { return DefaultMergeOption.ToEFMergeOption(); }
        }
    
        public bool UseWAQSProvider { get; set; }
    
        public Expression TransformExpression(Expression expression)
        {
            if (! UseWAQSProvider)
                return expression;
            Func<Expression, MethodCallExpression, MemberInfo, string, Expression, Expression> transformContinuation = (e, mce, memberInfo, memberName, objectExpression) =>
                {
                    if (memberInfo.DeclaringType == typeof(Entity1))
                    {
                        if (memberName == "NameLength" && (mce == null || mce.Method.GetParameters().Count() == 0))
                        {
                            var value = (Expression<Func<WebApplication1.Entity1, int>>)TransformExpression(WebApplication1.DAL.Entity1DALSpecifications.GetNameLengthExpression());
                            var memberAccessExpression = objectExpression as MemberExpression;
                            if (memberAccessExpression != null && memberAccessExpression.Expression is ConstantExpression && memberAccessExpression.Member.MemberType == MemberTypes.Field)
                                return Expression.Constant(value.Compile()(Expression.Lambda<Func<WebApplication1.Entity1>>(objectExpression).Compile()()), typeof(int));
                            return (value.Body.ReplaceParameter(pe => 
                                {
                                    if (pe == value.Parameters[0])
                                        return TransformExpression(objectExpression);
                                    return pe;
                                }));
                        }
                    }
                    return e;
                };
    
            return new ExpressionExtension.ExpressionReplaceRewriter
                {
                    ReplaceMethodCallFunc = mce =>
                        {
                            if (mce.Method.GetCustomAttributes(typeof(IncludeMethodAttribute), false).Any())
                                return mce;
                            MemberInfo memberInfo;
                            var value = WAQSL2EExpressionTransformation.TransformMethodCall(mce, this, TransformExpression);
                            if (value != mce)
                                return value;
                            memberInfo = mce.Method;
                            return transformContinuation(mce, mce, memberInfo, memberInfo.Name, mce.Object);
                        },
                    ReplaceBinaryFunc = be => WAQSL2EExpressionTransformation.TransformBinary(be, this, TransformExpression),
                    ReplaceMemberFunc = me =>
                        {
                            MemberInfo memberInfo;
                            if (!(memberInfo = me.Member).GetCustomAttributes(false).OfType<SpecificationsAttribute>().Any())
                                return WAQSL2EExpressionTransformation.TransformProperty(me, this, TransformExpression) ?? me;
                            return transformContinuation(me, null, memberInfo, memberInfo.Name, me.Expression);
                        }
                }.Visit(expression);
        }
        
        #region CSDL Functions
        [DbFunction("Edm", "CurrentDateTime")]
        public static DateTime GetDbCurrentDateTime()
        {
            return new WAQSModelContainer().GetDbDateTime();
        }
        Expression IObjectContext.GetDbDateTimeExpression()
        {
            return Expression.Call(typeof(WAQSModelContainer).GetMethod("GetDbCurrentDateTime"));
        }
        public DateTime GetDbDateTime()
        {
            return ExecuteFunction<Nullable<global::System.DateTime>>("GetDbDateTime").First().Value;
        }
    
        [DbFunction("Edm", "TruncateTime")]
        public static DateTime GetDate(DateTime dateTime)
        {
            return dateTime.Date;
        }
        Expression IObjectContext.GetDateExpression(Expression dateTimeExpresion)
        {
            return Expression.Call(typeof(WAQSModelContainer).GetMethod("GetDate"), dateTimeExpresion);
        }
    
        [DbFunction("Edm", "AddYears")]
        public static DateTime AddYears(DateTime dateTime, int years)
        {
            return dateTime.AddYears(years);
        }
        Expression IObjectContext.AddYearsExpression(Expression dateTimeExpresion, Expression yearsExpresion)
        {
            return Expression.Call(typeof(WAQSModelContainer).GetMethod("AddYears"), dateTimeExpresion, yearsExpresion);
        }
    
        [DbFunction("Edm", "AddYears")]
        public static DateTimeOffset AddYearsOffset(DateTimeOffset dateTime, int years)
        {
            return dateTime.AddYears(years);
        }
        Expression IObjectContext.AddYearsOffsetExpression(Expression dateTimeOffsetExpresion, Expression yearsExpresion)
        {
            return Expression.Call(typeof(WAQSModelContainer).GetMethod("AddYearsOffset"), dateTimeOffsetExpresion, yearsExpresion);
        }
    
        [DbFunction("Edm", "AddMonths")]
        public static DateTime AddMonths(DateTime dateTime, int months)
        {
            return dateTime.AddMonths(months);
        }
        Expression IObjectContext.AddMonthsExpression(Expression dateTimeExpresion, Expression monthsExpresion)
        {
            return Expression.Call(typeof(WAQSModelContainer).GetMethod("AddMonths"), dateTimeExpresion, monthsExpresion);
        }
    
        [DbFunction("Edm", "AddMonths")]
        public static DateTimeOffset AddMonthsOffset(DateTimeOffset dateTime, int months)
        {
            return dateTime.AddMonths(months);
        }
        Expression IObjectContext.AddMonthsOffsetExpression(Expression dateTimeOffsetExpresion, Expression yearsExpresion)
        {
            return Expression.Call(typeof(WAQSModelContainer).GetMethod("AddMonthsOffset"), dateTimeOffsetExpresion, yearsExpresion);
        }
    
        [DbFunction("Edm", "AddDays")]
        public static DateTime AddDays(DateTime dateTime, int days)
        {
            return dateTime.AddDays(days);
        }
        Expression IObjectContext.AddDaysExpression(Expression dateTimeExpresion, Expression daysExpresion)
        {
            return Expression.Call(typeof(WAQSModelContainer).GetMethod("AddDays"), dateTimeExpresion, daysExpresion);
        }
    
        [DbFunction("Edm", "AddDays")]
        public static DateTimeOffset AddDaysOffset(DateTimeOffset dateTime, int days)
        {
            return dateTime.AddDays(days);
        }
        Expression IObjectContext.AddDaysOffsetExpression(Expression dateTimeOffsetExpresion, Expression yearsExpresion)
        {
            return Expression.Call(typeof(WAQSModelContainer).GetMethod("AddDaysOffset"), dateTimeOffsetExpresion, yearsExpresion);
        }
    
        [DbFunction("Edm", "DiffDays")]
        public static int DiffDays(DateTime dateTime1, DateTime dateTime2)
        {
            return (dateTime1 - dateTime2).Days;
        }
        Expression IObjectContext.DiffDaysExpression(Expression dateTime1Expresion, Expression dateTime2Expresion)
        {
            return Expression.Call(typeof(WAQSModelContainer).GetMethod("DiffDays"), dateTime1Expresion, dateTime2Expresion);
        }
    
        [DbFunction("Edm", "DiffDays")]
        public static int DiffDaysOffset(DateTimeOffset dateTimeOffset1, DateTimeOffset dateTimeOffset2)
        {
            return (dateTimeOffset1 - dateTimeOffset2).Days;
        }
        Expression IObjectContext.DiffDaysOffsetExpression(Expression dateTimeOffset1Expresion, Expression dateTimeOffset2Expresion)
        {
            return Expression.Call(typeof(WAQSModelContainer).GetMethod("DiffDaysOffset"), dateTimeOffset1Expresion, dateTimeOffset2Expresion);
        }
    
        [DbFunction("Edm", "AddHours")]
        public static DateTime AddHours(DateTime dateTime, int hours)
        {
            return dateTime.AddHours(hours);
        }
        Expression IObjectContext.AddHoursExpression(Expression dateTimeExpresion, Expression hoursExpresion)
        {
            return Expression.Call(typeof(WAQSModelContainer).GetMethod("AddHours"), dateTimeExpresion, hoursExpresion);
        }
    
        [DbFunction("Edm", "AddHours")]
        public static DateTimeOffset AddHoursOffset(DateTimeOffset dateTime, int hours)
        {
            return dateTime.AddHours(hours);
        }
        Expression IObjectContext.AddHoursOffsetExpression(Expression dateTimeOffsetExpresion, Expression yearsExpresion)
        {
            return Expression.Call(typeof(WAQSModelContainer).GetMethod("AddHoursOffset"), dateTimeOffsetExpresion, yearsExpresion);
        }
    
        [DbFunction("Edm", "DiffHours")]
        public static int DiffHours(DateTime dateTime1, DateTime dateTime2)
        {
            return (dateTime1 - dateTime2).Hours;
        }
        Expression IObjectContext.DiffHoursExpression(Expression dateTime1Expresion, Expression dateTime2Expresion)
        {
            return Expression.Call(typeof(WAQSModelContainer).GetMethod("DiffHours"), dateTime1Expresion, dateTime2Expresion);
        }
    
        [DbFunction("Edm", "DiffHours")]
        public static int DiffHoursOffset(DateTimeOffset dateTimeOffset1, DateTimeOffset dateTimeOffset2)
        {
            return (dateTimeOffset1 - dateTimeOffset2).Hours;
        }
        Expression IObjectContext.DiffHoursOffsetExpression(Expression dateTimeOffset1Expresion, Expression dateTimeOffset2Expresion)
        {
            return Expression.Call(typeof(WAQSModelContainer).GetMethod("DiffHoursOffset"), dateTimeOffset1Expresion, dateTimeOffset2Expresion);
        }
    
        [DbFunction("Edm", "AddMinutes")]
        public static DateTime AddMinutes(DateTime dateTime, int minutes)
        {
            return dateTime.AddMinutes(minutes);
        }
        Expression IObjectContext.AddMinutesExpression(Expression dateTimeExpresion, Expression minutesExpresion)
        {
            return Expression.Call(typeof(WAQSModelContainer).GetMethod("AddMinutes"), dateTimeExpresion, minutesExpresion);
        }
    
        [DbFunction("Edm", "AddMinutes")]
        public static DateTimeOffset AddMinutesOffset(DateTimeOffset dateTime, int minutes)
        {
            return dateTime.AddMinutes(minutes);
        }
        Expression IObjectContext.AddMinutesOffsetExpression(Expression dateTimeOffsetExpresion, Expression yearsExpresion)
        {
            return Expression.Call(typeof(WAQSModelContainer).GetMethod("AddMinutesOffset"), dateTimeOffsetExpresion, yearsExpresion);
        }
    
        [DbFunction("Edm", "DiffMinutes")]
        public static int DiffMinutes(DateTime dateTime1, DateTime dateTime2)
        {
            return (dateTime1 - dateTime2).Minutes;
        }
        Expression IObjectContext.DiffMinutesExpression(Expression dateTime1Expresion, Expression dateTime2Expresion)
        {
            return Expression.Call(typeof(WAQSModelContainer).GetMethod("DiffMinutes"), dateTime1Expresion, dateTime2Expresion);
        }
        
        [DbFunction("Edm", "DiffMinutes")]
        public static int DiffMinutesOffset(DateTimeOffset dateTimeOffset1, DateTimeOffset dateTimeOffset2)
        {
            return (dateTimeOffset1 - dateTimeOffset2).Minutes;
        }
        Expression IObjectContext.DiffMinutesOffsetExpression(Expression dateTimeOffset1Expresion, Expression dateTimeOffset2Expresion)
        {
            return Expression.Call(typeof(WAQSModelContainer).GetMethod("DiffMinutesOffset"), dateTimeOffset1Expresion, dateTimeOffset2Expresion);
        }
    
        [DbFunction("Edm", "AddSeconds")]
        public static DateTime AddSeconds(DateTime dateTime, int seconds)
        {
            return dateTime.AddSeconds(seconds);
        }
        Expression IObjectContext.AddSecondsExpression(Expression dateTimeExpresion, Expression secondsExpresion)
        {
            return Expression.Call(typeof(WAQSModelContainer).GetMethod("AddSeconds"), dateTimeExpresion, secondsExpresion);
        }
        
        [DbFunction("Edm", "AddSeconds")]
        public static DateTimeOffset AddSecondsOffset(DateTimeOffset dateTime, int seconds)
        {
            return dateTime.AddSeconds(seconds);
        }
        Expression IObjectContext.AddSecondsOffsetExpression(Expression dateTimeOffsetExpresion, Expression yearsExpresion)
        {
            return Expression.Call(typeof(WAQSModelContainer).GetMethod("AddSecondsOffset"), dateTimeOffsetExpresion, yearsExpresion);
        }
    
        [DbFunction("Edm", "DiffSeconds")]
        public static int DiffSeconds(DateTime dateTime1, DateTime dateTime2)
        {
            return (dateTime1 - dateTime2).Seconds;
        }
        Expression IObjectContext.DiffSecondsExpression(Expression dateTime1Expresion, Expression dateTime2Expresion)
        {
            return Expression.Call(typeof(WAQSModelContainer).GetMethod("DiffSeconds"), dateTime1Expresion, dateTime2Expresion);
        }
    
        [DbFunction("Edm", "DiffSeconds")]
        public static int DiffSecondsOffset(DateTimeOffset dateTimeOffset1, DateTimeOffset dateTimeOffset2)
        {
            return (dateTimeOffset1 - dateTimeOffset2).Seconds;
        }
        Expression IObjectContext.DiffSecondsOffsetExpression(Expression dateTimeOffset1Expresion, Expression dateTimeOffset2Expresion)
        {
            return Expression.Call(typeof(WAQSModelContainer).GetMethod("DiffSecondsOffset"), dateTimeOffset1Expresion, dateTimeOffset2Expresion);
        }
    
        [DbFunction("Edm", "AddMilliseconds")]
        public static DateTime AddMilliseconds(DateTime dateTime, int milliseconds)
        {
            return dateTime.AddMilliseconds(milliseconds);
        }
        Expression IObjectContext.AddMillisecondsExpression(Expression dateTimeExpresion, Expression millisecondsExpresion)
        {
            return Expression.Call(typeof(WAQSModelContainer).GetMethod("AddMilliseconds"), dateTimeExpresion, millisecondsExpresion);
        }
    
        [DbFunction("Edm", "AddMilliseconds")]
        public static DateTimeOffset AddMillisecondsOffset(DateTimeOffset dateTime, int millisecond)
        {
            return dateTime.AddMilliseconds(millisecond);
        }
        Expression IObjectContext.AddMillisecondsOffsetExpression(Expression dateTimeOffsetExpresion, Expression yearsExpresion)
        {
            return Expression.Call(typeof(WAQSModelContainer).GetMethod("AddMillisecondsOffset"), dateTimeOffsetExpresion, yearsExpresion);
        }
    
        [DbFunction("Edm", "DiffMilliseconds")]
        public static int DiffMilliseconds(DateTime dateTime1, DateTime dateTime2)
        {
            return (dateTime1 - dateTime2).Milliseconds;
        }
        Expression IObjectContext.DiffMillisecondsExpression(Expression dateTime1Expresion, Expression dateTime2Expresion)
        {
            return Expression.Call(typeof(WAQSModelContainer).GetMethod("DiffMilliseconds"), dateTime1Expresion, dateTime2Expresion);
        }
    
        [DbFunction("Edm", "DiffMilliseconds")]
        public static int DiffMillisecondsOffset(DateTimeOffset dateTimeOffset1, DateTimeOffset dateTimeOffset2)
        {
            return (dateTimeOffset1 - dateTimeOffset2).Milliseconds;
        }
        Expression IObjectContext.DiffMillisecondsOffsetExpression(Expression dateTimeOffset1Expresion, Expression dateTimeOffset2Expresion)
        {
            return Expression.Call(typeof(WAQSModelContainer).GetMethod("DiffMillisecondsOffset"), dateTimeOffset1Expresion, dateTimeOffset2Expresion);
        }
    
        [DbFunction("Edm", "Abs")]
        public static short AbsInt16(short value)
        {
            return Math.Abs(value);
        }
        Expression IObjectContext.AbsInt16Expression(Expression value)
        {
            return Expression.Call(typeof(WAQSModelContainer).GetMethod("AbsInt16"), value);
        }
    
        [DbFunction("Edm", "Abs")]
        public static int AbsInt32(int value)
        {
            return Math.Abs(value);
        }
        Expression IObjectContext.AbsInt32Expression(Expression value)
        {
            return Expression.Call(typeof(WAQSModelContainer).GetMethod("AbsInt32"), value);
        }
    
        [DbFunction("Edm", "Abs")]
        public static long AbsInt64(long value)
        {
            return Math.Abs(value);
        }
        Expression IObjectContext.AbsInt64Expression(Expression value)
        {
            return Expression.Call(typeof(WAQSModelContainer).GetMethod("AbsInt64"), value);
        }
    
        [DbFunction("Edm", "Abs")]
        public static float AbsSingle(float value)
        {
            return Math.Abs(value);
        }
        Expression IObjectContext.AbsSingleExpression(Expression value)
        {
            return Expression.Call(typeof(WAQSModelContainer).GetMethod("AbsIntSingle"), value);
        }
    
        [DbFunction("Edm", "Abs")]
        public static double AbsDouble(double value)
        {
            return Math.Abs(value);
        }
        Expression IObjectContext.AbsDoubleExpression(Expression value)
        {
            return Expression.Call(typeof(WAQSModelContainer).GetMethod("AbsDouble"), value);
        }
    
        [DbFunction("Edm", "Abs")]
        public static decimal AbsDecimal(decimal value)
        {
            return Math.Abs(value);
        }
        Expression IObjectContext.AbsDecimalExpression(Expression value)
        {
            return Expression.Call(typeof(WAQSModelContainer).GetMethod("AbsDecimal"), value);
        }
    
        [DbFunction("Edm", "Ceiling")]
        public static double CeilingDouble(double value)
        {
            return Math.Ceiling(value);
        }
        Expression IObjectContext.CeilingDoubleExpression(Expression value)
        {
            return Expression.Call(typeof(WAQSModelContainer).GetMethod("CeilingDouble"), value);
        }
    
        [DbFunction("Edm", "Ceiling")]
        public static decimal CeilingDecimal(decimal value)
        {
            return Math.Ceiling(value);
        }
        Expression IObjectContext.CeilingDecimalExpression(Expression value)
        {
            return Expression.Call(typeof(WAQSModelContainer).GetMethod("CeilingDecimal"), value);
        }
    
        [DbFunction("Edm", "Floor")]
        public static double FloorDouble(double value)
        {
            return Math.Floor(value);
        }
        Expression IObjectContext.FloorDoubleExpression(Expression value)
        {
            return Expression.Call(typeof(WAQSModelContainer).GetMethod("FloorDouble"), value);
        }
    
        [DbFunction("Edm", "Floor")]
        public static decimal FloorDecimal(decimal value)
        {
            return Math.Floor(value);
        }
        Expression IObjectContext.FloorDecimalExpression(Expression value)
        {
            return Expression.Call(typeof(WAQSModelContainer).GetMethod("FloorDecimal"), value);
        }
    
        [DbFunction("Edm", "Power")]
        public static double PowDouble(double value, double exponent)
        {
            return Math.Pow(value, exponent);
        }
        [DbFunction("Edm", "Power")]
        public static decimal PowDecimal(decimal value, decimal exponent)
        {
            return (decimal)Math.Pow((double)value, (double)exponent);
        }
        Expression IObjectContext.PowDoubleExpression(Expression value, Expression exponent)
        {
            return Expression.Call(typeof(WAQSModelContainer).GetMethod("PowDouble"), value, exponent);
        }
    
        [DbFunction("Edm", "Round")]
        public static double RoundAwayFromZeroDouble(double value)
        {
            return Math.Round(value);
        }
        Expression IObjectContext.RoundToEvenDoubleExpression(Expression value)
        {
            return Expression.Condition(
                Expression.AndAlso(
                    Expression.Equal(
                        Expression.Modulo(
                            Expression.Convert(
                                Expression.Call(
                                    typeof(WAQSModelContainer).GetMethod("AbsDouble"),
                                    Expression.Multiply(
                                        value,
                                        Expression.Constant(10.0))),
                                typeof(int)),
                            Expression.Constant(10)),
                        Expression.Constant(5)),
                    Expression.Equal(
                        Expression.Modulo(
                            Expression.Convert(
                                Expression.Call(
                                    typeof(WAQSModelContainer).GetMethod("TruncateDouble"),
                                    value,
                                    Expression.Constant(0)),
                                typeof(int)),
                            Expression.Constant(2)),
                        Expression.Constant(0))),
                Expression.Add(
                    Expression.Call(
                        typeof(WAQSModelContainer).GetMethod("RoundAwayFromZeroDouble", new Type[] { typeof(double) } ),
                        value),
                    Expression.Condition(
                        Expression.GreaterThanOrEqual(
                            value,
                            Expression.Constant(0.0)),
                        Expression.Constant(-1.0),
                        Expression.Constant(1.0))),
                Expression.Call(
                    typeof(WAQSModelContainer).GetMethod("RoundAwayFromZeroDouble", new Type[] { typeof(double) } ),
                    value));
        }
        Expression IObjectContext.RoundAwayFromZeroDoubleExpression(Expression value)
        {
            return Expression.Call(typeof(WAQSModelContainer).GetMethod("RoundAwayFromZeroDouble", new Type[] { typeof(double) } ), value);
        }
    
        [DbFunction("Edm", "Round")]
        public static decimal RoundAwayFromZeroDecimal(decimal value)
        {
            return Math.Round(value);
        }
        Expression IObjectContext.RoundToEvenDecimalExpression(Expression value)
        {
            return Expression.Condition(
                Expression.AndAlso(
                    Expression.Equal(
                        Expression.Modulo(
                            Expression.Convert(
                                Expression.Call(
                                    typeof(WAQSModelContainer).GetMethod("AbsDecimal"),
                                    Expression.Multiply(
                                        value,
                                        Expression.Constant(10.0))),
                                typeof(int)),
                            Expression.Constant(10)),
                        Expression.Constant(5)),
                    Expression.Equal(
                        Expression.Modulo(
                            Expression.Convert(
                                Expression.Call(
                                    typeof(WAQSModelContainer).GetMethod("TruncateDecimal"),
                                    value,
                                    Expression.Constant(0)),
                                typeof(int)),
                            Expression.Constant(2)),
                        Expression.Constant(0))),
                Expression.Add(
                    Expression.Call(
                        typeof(WAQSModelContainer).GetMethod("RoundAwayFromZeroDecimal", new Type[] { typeof(double) } ),
                        value),
                    Expression.Condition(
                        Expression.GreaterThanOrEqual(
                            value,
                            Expression.Constant(0M)),
                        Expression.Constant(-1M),
                        Expression.Constant(1M))),
                Expression.Call(
                    typeof(WAQSModelContainer).GetMethod("RoundAwayFromZeroDecimal", new Type[] { typeof(double) } ),
                    value));
        }
        Expression IObjectContext.RoundAwayFromZeroDecimalExpression(Expression value)
        {
            return Expression.Call(typeof(WAQSModelContainer).GetMethod("RoundAwayFromZeroDecimal", new Type[] { typeof(decimal) }), value);
        }
    
        [DbFunction("Edm", "Round")]
        public static double RoundAwayFromZeroDouble(double value, int digits)
        {
            return Math.Round(value, digits);
        }
        Expression IObjectContext.RoundToEvenDoubleExpression(Expression value, Expression digits)
        {
            return Expression.Condition(
                Expression.AndAlso(
                    Expression.Equal(
                        Expression.Modulo(
                            Expression.Convert(
                                Expression.Call(
                                    typeof(WAQSModelContainer).GetMethod("AbsDouble"),
                                    Expression.Multiply(
                                        value,
                                        Expression.Call(
                                            typeof(WAQSModelContainer).GetMethod("PowDouble"),
                                            Expression.Constant(10.0),
                                            Expression.Add(
                                                Expression.Convert(digits, typeof(double)),
                                                Expression.Constant(1.0))))),
                                typeof(int)),
                            Expression.Constant(10)),
                        Expression.Constant(5)),
                    Expression.Equal(
                        Expression.Modulo(
                            Expression.Convert(
                                Expression.Call(
                                    typeof(WAQSModelContainer).GetMethod("TruncateDouble"),
                                    Expression.Multiply(
                                        value,
                                        Expression.Call(
                                            typeof(WAQSModelContainer).GetMethod("PowDouble"),
                                            Expression.Constant(10.0),
                                            Expression.Convert(digits, typeof(double)))),
                                    Expression.Constant(0)),
                                typeof(int)),
                            Expression.Constant(2)),
                        Expression.Constant(0))),
                Expression.Add(
                    Expression.Call(
                        typeof(WAQSModelContainer).GetMethod("RoundAwayFromZeroDouble", new Type[] { typeof(double), typeof(int) }),
                        value,
                        digits),
                    Expression.Divide(
                        Expression.Condition(
                            Expression.GreaterThanOrEqual(
                                value,
                                Expression.Constant(0.0)),
                            Expression.Constant(-1.0),
                            Expression.Constant(1.0)),
                        Expression.Call(
                            typeof(WAQSModelContainer).GetMethod("PowDouble"),
                            Expression.Constant(10.0),
                            Expression.Convert(digits, typeof(double))))),
                Expression.Call(
                    typeof(WAQSModelContainer).GetMethod("RoundAwayFromZeroDouble", new Type[] { typeof(double), typeof(int) }),
                    value,
                    digits));
        }
        Expression IObjectContext.RoundAwayFromZeroDoubleExpression(Expression value, Expression digits)
        {
            return Expression.Call(typeof(WAQSModelContainer).GetMethod("RoundAwayFromZeroDouble", new Type[] { typeof(double), typeof(int) }), value, digits);
        }
    
        [DbFunction("Edm", "Round")]
        public static decimal RoundAwayFromZeroDecimal(decimal value, int digits)
        {
            return Math.Round(value, digits);
        }
        Expression IObjectContext.RoundToEvenDecimalExpression(Expression value, Expression digits)
        {
            return Expression.Condition(
                Expression.AndAlso(
                    Expression.Equal(
                        Expression.Modulo(
                            Expression.Convert(
                                Expression.Call(
                                    typeof(WAQSModelContainer).GetMethod("AbsDecimal"),
                                    Expression.Multiply(
                                        value,
                                        Expression.Call(
                                            typeof(WAQSModelContainer).GetMethod("PowDecimal"),
                                            Expression.Constant(10M),
                                            Expression.Add(
                                                Expression.Convert(digits, typeof(decimal)),
                                                Expression.Constant(1M))))),
                                typeof(int)),
                            Expression.Constant(10)),
                        Expression.Constant(5)),
                    Expression.Equal(
                        Expression.Modulo(
                            Expression.Convert(
                                Expression.Call(
                                    typeof(WAQSModelContainer).GetMethod("TruncateDecimal"),
                                    Expression.Multiply(
                                        value,
                                        Expression.Call(
                                            typeof(WAQSModelContainer).GetMethod("PowDecimal"),
                                            Expression.Constant(10M),
                                            Expression.Convert(digits, typeof(decimal)))),
                                    Expression.Constant(0)),
                                typeof(int)),
                            Expression.Constant(2)),
                        Expression.Constant(0))),
                Expression.Add(
                    Expression.Call(
                        typeof(WAQSModelContainer).GetMethod("RoundAwayFromZeroDecimal", new Type[] { typeof(decimal), typeof(int) }),
                        value,
                        digits),
                    Expression.Divide(
                        Expression.Condition(
                            Expression.GreaterThanOrEqual(
                                value,
                                Expression.Constant(0M)),
                            Expression.Constant(-1M),
                            Expression.Constant(1M)),
                        Expression.Call(
                            typeof(WAQSModelContainer).GetMethod("PowDecimal"),
                            Expression.Constant(10M),
                            Expression.Convert(digits, typeof(decimal))))),
                Expression.Call(
                    typeof(WAQSModelContainer).GetMethod("RoundAwayFromZeroDecimal", new Type[] { typeof(decimal), typeof(int) }),
                    value,
                    digits));
        }
        Expression IObjectContext.RoundAwayFromZeroDecimalExpression(Expression value, Expression digits)
        {
            return Expression.Call(typeof(WAQSModelContainer).GetMethod("RoundAwayFromZeroDecimal", new Type[] { typeof(decimal), typeof(int) }), value, digits);
        }
    
        [DbFunction("Edm", "Truncate")]
        public static double TruncateDouble(double value, int digits)
        {
            if (digits != 0)
                throw new InvalidOperationException();
            return Math.Truncate(value);
        }
        Expression IObjectContext.TruncateDoubleExpression(Expression value)
        {
            return Expression.Call(typeof(WAQSModelContainer).GetMethod("TruncateDouble"), value, Expression.Constant(0, typeof(int)));
        }
    
        [DbFunction("Edm", "Truncate")]
        public static decimal TruncateDecimal(decimal value, int digits)
        {
            if (digits != 0)
                throw new InvalidOperationException();
            return Math.Truncate(value);
        }
        Expression IObjectContext.TruncateDecimalExpression(Expression value)
        {
            return Expression.Call(typeof(WAQSModelContainer).GetMethod("TruncateDecimal"), value, Expression.Constant(0, typeof(int)));
        }
    
        [DbFunction(namespaceName: "WAQSModel", functionName: "LessThanString")]
        public static bool LessThanString(string s1, string s2)
        {
            throw new NotImplementedException();
        }
        Expression IObjectContext.LessThanString(Expression s1Expresion, Expression s2Expresion)
        {
            return Expression.Call(typeof(WAQSModelContainer).GetMethod("LessThanString"), s1Expresion, s2Expresion);
        }
    
        [DbFunction(namespaceName: "WAQSModel", functionName: "GreaterThanString")]
        public static bool GreaterThanString(string s1, string s2)
        {
            throw new NotImplementedException();
        }
        Expression IObjectContext.GreaterThanString(Expression s1Expresion, Expression s2Expresion)
        {
            return Expression.Call(typeof(WAQSModelContainer).GetMethod("GreaterThanString"), s1Expresion, s2Expresion);
        }
        #endregion
    
        #region AdditionalProperties
        DateTime IObjectContext.DbDateTime
        {
            get { return DateTime.Now; }
        }
        #endregion AdditionalProperties
    
        #region Specifications
        private IEntity1DALSpecifications _entity1DALSpecifications;
        private IEntity1DALSpecifications Entity1DALSpecifications
        {
            get { return _entity1DALSpecifications ?? (_entity1DALSpecifications = new Entity1DALSpecifications(this)); }
        }
        IEntity1DALSpecifications IWAQSModelContainer.Entity1DALSpecifications
        {
            get { return Entity1DALSpecifications; }
        }

        #endregion

        
        void IDataContext.SaveChanges(bool acceptChanges)
        {
            var saveOption = acceptChanges ? SaveOptions.AcceptAllChangesAfterSave : SaveOptions.None;
            if (UseWAQSProvider)
                saveOption |= SaveOptions.DetectChangesBeforeSave;
            SaveChanges(saveOption);
        }
    
        void IDataContext.ApplyChanges<TEntity>(IEntitySet<TEntity> entitySet, TEntity entity)
        {
            ((EntitySet<TEntity>)entitySet).ObjectSet.ApplyChanges(entity);
        }
    
        void IDataContext.LoadMetadata()
        {
            MetadataWorkspace.LoadFromAssembly(typeof(WAQSModelContainer).Assembly);
        }
    
        private Dictionary<Tuple<Type, string>, Lazy<Func<ParameterExpression, Expression>>> _propertiesExpressions;
        Expression IDataContext.GetExpression(Type type, string propertyName, ParameterExpression parameterExpression)
        {
            if (_propertiesExpressions == null)
            {
                _propertiesExpressions = new Dictionary<Tuple<Type, string>, Lazy<Func<ParameterExpression, Expression>>>();
                {
                    _propertiesExpressions.Add(new Tuple<Type, string>(typeof(Entity1), "NameLength"), new Lazy<Func<ParameterExpression, Expression>>(() => 
                    {
                        LambdaExpression exp = Entity1DALSpecifications.NameLengthExpression;
                        return p => exp.Body.ReplaceParameter(exp.Parameters[0], p);
                    }));
                }
            }
            Lazy<Func<ParameterExpression, Expression>> result = null;
            while (type != null && ! _propertiesExpressions.TryGetValue(new Tuple<Type, string>(type, propertyName), out result))
                type = type.BaseType;
            if (type == null)
                throw new NotImplementedException();
            return result.Value(parameterExpression);
        }
    
    
        private Dictionary<Tuple<Type, string>, Lazy<Func<List<Expression>, ParameterExpression, Expression>>> _methodsExpressions;
        Expression IDataContext.GetExpression(Type type, string methodName, List<Expression> arguments, ParameterExpression parameterExpression)
        {
            if (_methodsExpressions == null)
            {
                _methodsExpressions = new Dictionary<Tuple<Type, string>, Lazy<Func<List<Expression>, ParameterExpression, Expression>>>();
            }
            Lazy<Func<List<Expression>, ParameterExpression, Expression>> result = null;
            while (type != null && !_methodsExpressions.TryGetValue(new Tuple<Type, string>(type, methodName), out result))
                type = type.BaseType;
            if (type == null)
                throw new NotImplementedException();
            return result.Value(arguments, parameterExpression);
        }
    
        void IDataContext.AttachRelationship<TEntity1, TEntity2>(TEntity1 entity1, TEntity2 entity2, string collectionName)
        {
            ObjectStateEntry entity1OSE;
            if (ObjectStateManager.TryGetObjectStateEntry(entity1, out entity1OSE))
            {
            }
        }
        
    
        async Task IDataContext.SaveChangesAsync(bool acceptChanges)
        {
            var saveOption = acceptChanges ? SaveOptions.AcceptAllChangesAfterSave : SaveOptions.None;
            if (UseWAQSProvider)
                saveOption |= SaveOptions.DetectChangesBeforeSave;
            await SaveChangesAsync(saveOption);
        }
    }
}
