//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// Copyright (c) Matthieu MEZIL.  All rights reserved.
// matthieu.mezil@live.fr

 
using System;
using System.Collections.Generic;
using System.Linq;
using System.ServiceModel.Activation;
using WCFAsyncQueryableServices.Common;
using WCFAsyncQueryableServices.SerializableExpressions;
using WCFAsyncQueryableServices.Service.Interfaces;
using WCFAsyncQueryableServices.WCFService;
using WCFAsyncQueryableServices.WCFService.Contract;
using WebApplication1;
using WebApplication1.Service.Interfaces;
using WebApplication1.WCFService.Contract;

namespace WebApplication1.WCFService
{
    [AspNetCompatibilityRequirements(RequirementsMode = AspNetCompatibilityRequirementsMode.Required)]
    public partial class WAQSModelWCFService : IWAQSModelWCFService
    {	
    	private Func<IWAQSModelService> _serviceFactory;
    	private Dictionary<Type, IExceptionDetailFactory> _exceptionDetailFactories;
    
    	public WAQSModelWCFService(Func<IWAQSModelService> serviceFactory, WCFAsyncQueryableServices.Common.IExceptionDetailFactory[] exceptionDetailFactories)
    	{
    		_serviceFactory = serviceFactory;
    		_exceptionDetailFactories = exceptionDetailFactories.ToDictionary(ed => ed.Type);
    	}
    	
    	private void TryRethrowFault(Action action)
    	{
    		Action<Action> metaRethrow = null;
    		TryMetaRethrow(ref metaRethrow);
    		if (metaRethrow == null)
    			WCFAsyncQueryableServices.WCFService.WCFService.TryRethrowFault(action, _exceptionDetailFactories, CreateFaultDetail, fd => DefineFaultDetail(fd));
    		else
    			metaRethrow(() => WCFAsyncQueryableServices.WCFService.WCFService.TryRethrowFault(action, _exceptionDetailFactories, CreateFaultDetail, fd => DefineFaultDetail(fd)));
    	}
    	partial void TryMetaRethrow(ref Action<Action> action);
    	
    	private T TryRethrowFault<T>(Func<T> action)
    	{
    		Func<Func<T>, T> metaRethrow = null;
    		TryMetaRethrow(ref metaRethrow);
    		if (metaRethrow == null)
    			return WCFAsyncQueryableServices.WCFService.WCFService.TryRethrowFault(action, _exceptionDetailFactories, CreateFaultDetail, fd => DefineFaultDetail(fd));
    		return metaRethrow(() => WCFAsyncQueryableServices.WCFService.WCFService.TryRethrowFault(action, _exceptionDetailFactories, CreateFaultDetail, fd => DefineFaultDetail(fd)));
    	}
    	partial void TryMetaRethrow<T>(ref Func<Func<T>, T> action);
    
    	private FaultDetail CreateFaultDetail(WCFAsyncQueryableServices.Common.IExceptionDetail exceptionDetail)
    	{
    		var entities = exceptionDetail.Entities.ToList();
    		if (entities.Count == 0)
    			return new FaultDetail { ErrorMessage = exceptionDetail.Message };
    		return new WAQSModelFaultDetailEntities { ErrorMessage = exceptionDetail.Message, Entities = entities };
    	}
    
    	partial void DefineFaultDetail(FaultDetail faultDetail);
    
    
    	public WAQSModelQueryResult Execute(QuerySerialization query)
    	{
    		Executing(query);
    		return TryRethrowFault(() => 
    			{
    				using (var service = _serviceFactory())
    				{
    					return service.Execute(query);
    				}
    			});
    	}
    	partial void Executing(QuerySerialization query);
    
    	public WAQSModelQueriesResult ExecuteMany(QueriesSerialization queries)
    	{
    		Executing(queries);
    		return TryRethrowFault(() => 
    			{
    				using (var service = _serviceFactory())
    				{
    					return service.ExecuteMany(queries);
    				}
    			});
    	}
    	partial void Executing(QueriesSerialization queries);
    
    	public WAQSModelQueryResultPage LoadPage(int pageSize, SerializableExpression queryExpression, string[] withSpecificationsProperties, LoadPageParameter[] identifiers)
    	{
    		LoadingPage(pageSize, queryExpression, withSpecificationsProperties, identifiers);
    		return TryRethrowFault(() =>
    		{
    			using (var service = _serviceFactory())
    			{
    				return service.LoadPage(pageSize, queryExpression, withSpecificationsProperties, identifiers);
    			}
    		});
    	}
    	partial void LoadingPage(int pageSize, SerializableExpression queryExpression, string[] withSpecificationsProperties, LoadPageParameter[] identifiers);
    
    	public DateTime GetDbDateTime()
    	{
    		return TryRethrowFault(() => 
    			{
    				using (var service = _serviceFactory())
    				{
    					return service.GetDbDateTime();
    				}
    			});
    	}
    
    	public WAQSModelSerializableContext SaveChanges(WAQSModelSerializableContext clientContext)
    	{
    		SavingChanges(clientContext);
    		return TryRethrowFault(() => 
    			{
    				using (var service = _serviceFactory())
    				{
    					foreach (var entity in clientContext.Entity1)
    						service.ApplyChanges(entity);
    					service.SaveChanges();
    					return clientContext;
    				}
    			});
    	}
    	partial void SavingChanges(WAQSModelSerializableContext clientContext);
    
    	public List<Error> Validate(Entity1 entity)
    	{
    		return TryRethrowFault(() => 
    			{
    				using (var service = _serviceFactory())
    				{
    					return service.Validate(entity).ToList();
    				}
    			});
    	}
    }
    
}
