//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// Copyright (c) Matthieu MEZIL.  All rights reserved.
// matthieu.mezil@live.fr

 
using System;
using System.Linq.Expressions;
using WCFAsyncQueryableServices.Service;
using WebApplication1;
using WebApplication1.DAL.Interfaces;

namespace WebApplication1.Service
{
    public partial class WAQSModelEntitiesFilters
    {
        private readonly IWAQSModelContainer _context;
    
        public WAQSModelEntitiesFilters(IWAQSModelContainer context)
        {
            _context = context;
        }
    
        private Expression<Func<Entity1, bool>> _entity1FilterExpression;
        private bool _entity1FilterExpressionInitialized = false;
        public Expression<Func<Entity1, bool>> Entity1FilterExpression
        {
            get 
            { 
                if (!_entity1FilterExpressionInitialized)
                {
                    ApplyEntity1ServerWhere(ref _entity1FilterExpression);
                    _entity1FilterExpressionInitialized = true;
                }
                return _entity1FilterExpression;
            }
        }
        partial void ApplyEntity1ServerWhere(ref Expression<Func<Entity1, bool>> filterExpression);
    
    }
}
