// Copyright (c) Matthieu MEZIL.  All rights reserved.
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://WCFAsyncQueryableServices/Query", ClrNamespace = "WCFAsyncQueryableServices.ClientContext.Interfaces.Query")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://WCFAsyncQueryableServices/QuerySerialization", ClrNamespace = "WCFAsyncQueryableServices.ClientContext.Interfaces.ExpressionSerialization")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://WAQSModel/SerializableContext", ClrNamespace = "WAQSTest.ClientContext.Interfaces.Serialization")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://WAQSModel/Entities", ClrNamespace = "WAQSTest")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://WCFAsyncQueryableServices/EntityTracking", ClrNamespace = "WCFAsyncQueryableServices.EntitiesTracking")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://WCFAsyncQueryableServices/Querying", ClrNamespace = "WCFAsyncQueryableServices.ClientContext.Interfaces.Querying")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://WCFAsyncQueryableServices/QueryResult", ClrNamespace = "WCFAsyncQueryableServices.ClientContext.QueryResult")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://WAQSModel/QueryResult", ClrNamespace = "WAQSTest.ClientContext.QueryResult")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://WAQSModel/Fault", ClrNamespace = "WAQSTest.ClientContext.Fault")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://WCFAsyncQueryableServices/Fault", ClrNamespace = "WCFAsyncQueryableServices.ClientContext.Fault")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://WCFAsyncQueryableServices/Errors", ClrNamespace = "WCFAsyncQueryableServices.ClientContext.Interfaces.Errors")]
// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.60310.0
// 
namespace WAQSTest.ClientContext.ServiceReference
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://WAQSModel.net", ConfigurationName = "WAQSTest.ClientContext.ServiceReference.IWAQSModelService")]
    public interface IWAQSModelService : System.ServiceModel.ICommunicationObject, System.IDisposable
    {
        [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "http://WAQSModel.net/IWAQSModelService/Execute", ReplyAction = "http://WAQSModel.net/IWAQSModelService/ExecuteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof (WCFAsyncQueryableServices.ClientContext.Fault.FaultDetail), Action = "FaultDetail", Name = "FaultDetail", Namespace = "")]
        [System.ServiceModel.FaultContractAttribute(typeof (WCFAsyncQueryableServices.ClientContext.Interfaces.Errors.Error), Action = "Error", Name = "Error", Namespace = "")]
        [System.ServiceModel.FaultContractAttribute(typeof (WCFAsyncQueryableServices.ClientContext.Fault.ErrorCollection), Action = "ErrorCollection", Name = "ErrorCollection", Namespace = "")]
        [System.ServiceModel.FaultContractAttribute(typeof (WAQSTest.ClientContext.Fault.WAQSModelFaultDetailEntities), Action = "WAQSModelFaultDetailEntities", Name = "WAQSModelFaultDetailEntities", Namespace = "")]
        System.IAsyncResult BeginExecute(WCFAsyncQueryableServices.ClientContext.Interfaces.Query.QuerySerialization query, System.AsyncCallback callback, object asyncState);
        WAQSTest.ClientContext.QueryResult.WAQSModelQueryResult EndExecute(System.IAsyncResult result);
        [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "http://WAQSModel.net/IWAQSModelService/ExecuteMany", ReplyAction = "http://WAQSModel.net/IWAQSModelService/ExecuteManyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof (WCFAsyncQueryableServices.ClientContext.Fault.FaultDetail), Action = "FaultDetail", Name = "FaultDetail", Namespace = "")]
        [System.ServiceModel.FaultContractAttribute(typeof (WCFAsyncQueryableServices.ClientContext.Interfaces.Errors.Error), Action = "Error", Name = "Error", Namespace = "")]
        [System.ServiceModel.FaultContractAttribute(typeof (WCFAsyncQueryableServices.ClientContext.Fault.ErrorCollection), Action = "ErrorCollection", Name = "ErrorCollection", Namespace = "")]
        [System.ServiceModel.FaultContractAttribute(typeof (WAQSTest.ClientContext.Fault.WAQSModelFaultDetailEntities), Action = "WAQSModelFaultDetailEntities", Name = "WAQSModelFaultDetailEntities", Namespace = "")]
        System.IAsyncResult BeginExecuteMany(WCFAsyncQueryableServices.ClientContext.Interfaces.Query.QueriesSerialization queries, System.AsyncCallback callback, object asyncState);
        WAQSTest.ClientContext.QueryResult.WAQSModelQueriesResult EndExecuteMany(System.IAsyncResult result);
        [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "http://WAQSModel.net/IWAQSModelService/LoadPage", ReplyAction = "http://WAQSModel.net/IWAQSModelService/LoadPageResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof (WCFAsyncQueryableServices.ClientContext.Fault.FaultDetail), Action = "FaultDetail", Name = "FaultDetail", Namespace = "")]
        [System.ServiceModel.FaultContractAttribute(typeof (WCFAsyncQueryableServices.ClientContext.Interfaces.Errors.Error), Action = "Error", Name = "Error", Namespace = "")]
        [System.ServiceModel.FaultContractAttribute(typeof (WCFAsyncQueryableServices.ClientContext.Fault.ErrorCollection), Action = "ErrorCollection", Name = "ErrorCollection", Namespace = "")]
        [System.ServiceModel.FaultContractAttribute(typeof (WAQSTest.ClientContext.Fault.WAQSModelFaultDetailEntities), Action = "WAQSModelFaultDetailEntities", Name = "WAQSModelFaultDetailEntities", Namespace = "")]
        System.IAsyncResult BeginLoadPage(int pageSize, WCFAsyncQueryableServices.ClientContext.Interfaces.ExpressionSerialization.SerializableExpression queryExpression, string[] withSpecificationsProperties, WCFAsyncQueryableServices.ClientContext.Interfaces.Querying.LoadPageParameter[] identifiers, System.AsyncCallback callback, object asyncState);
        WAQSTest.ClientContext.QueryResult.WAQSModelQueryResultPage EndLoadPage(System.IAsyncResult result);
        [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "http://WAQSModel.net/IWAQSModelService/GetDbDateTime", ReplyAction = "http://WAQSModel.net/IWAQSModelService/GetDbDateTimeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof (WCFAsyncQueryableServices.ClientContext.Fault.FaultDetail), Action = "FaultDetail", Name = "FaultDetail", Namespace = "")]
        [System.ServiceModel.FaultContractAttribute(typeof (WCFAsyncQueryableServices.ClientContext.Interfaces.Errors.Error), Action = "Error", Name = "Error", Namespace = "")]
        [System.ServiceModel.FaultContractAttribute(typeof (WCFAsyncQueryableServices.ClientContext.Fault.ErrorCollection), Action = "ErrorCollection", Name = "ErrorCollection", Namespace = "")]
        [System.ServiceModel.FaultContractAttribute(typeof (WAQSTest.ClientContext.Fault.WAQSModelFaultDetailEntities), Action = "WAQSModelFaultDetailEntities", Name = "WAQSModelFaultDetailEntities", Namespace = "")]
        System.IAsyncResult BeginGetDbDateTime(System.AsyncCallback callback, object asyncState);
        System.DateTime EndGetDbDateTime(System.IAsyncResult result);
        [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "http://WAQSModel.net/IWAQSModelService/SaveChanges", ReplyAction = "http://WAQSModel.net/IWAQSModelService/SaveChangesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof (WCFAsyncQueryableServices.ClientContext.Fault.FaultDetail), Action = "FaultDetail", Name = "FaultDetail", Namespace = "")]
        [System.ServiceModel.FaultContractAttribute(typeof (WCFAsyncQueryableServices.ClientContext.Interfaces.Errors.Error), Action = "Error", Name = "Error", Namespace = "")]
        [System.ServiceModel.FaultContractAttribute(typeof (WCFAsyncQueryableServices.ClientContext.Fault.ErrorCollection), Action = "ErrorCollection", Name = "ErrorCollection", Namespace = "")]
        [System.ServiceModel.FaultContractAttribute(typeof (WAQSTest.ClientContext.Fault.WAQSModelFaultDetailEntities), Action = "WAQSModelFaultDetailEntities", Name = "WAQSModelFaultDetailEntities", Namespace = "")]
        System.IAsyncResult BeginSaveChanges(WAQSTest.ClientContext.Interfaces.Serialization.WAQSModelSerializableContext context, System.AsyncCallback callback, object asyncState);
        WAQSTest.ClientContext.Interfaces.Serialization.WAQSModelSerializableContext EndSaveChanges(System.IAsyncResult result);
        [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "http://WAQSModel.net/IWAQSModelService/ValidateEntity1", ReplyAction = "http://WAQSModel.net/IWAQSModelService/ValidateEntity1Response")]
        [System.ServiceModel.FaultContractAttribute(typeof (WCFAsyncQueryableServices.ClientContext.Fault.FaultDetail), Action = "FaultDetail", Name = "FaultDetail", Namespace = "")]
        [System.ServiceModel.FaultContractAttribute(typeof (WCFAsyncQueryableServices.ClientContext.Interfaces.Errors.Error), Action = "Error", Name = "Error", Namespace = "")]
        [System.ServiceModel.FaultContractAttribute(typeof (WCFAsyncQueryableServices.ClientContext.Fault.ErrorCollection), Action = "ErrorCollection", Name = "ErrorCollection", Namespace = "")]
        [System.ServiceModel.FaultContractAttribute(typeof (WAQSTest.ClientContext.Fault.WAQSModelFaultDetailEntities), Action = "WAQSModelFaultDetailEntities", Name = "WAQSModelFaultDetailEntities", Namespace = "")]
        System.IAsyncResult BeginValidateEntity1(WAQSTest.Entity1 entity, System.AsyncCallback callback, object asyncState);
        WCFAsyncQueryableServices.ClientContext.Interfaces.Errors.Error[] EndValidateEntity1(System.IAsyncResult result);
    }
}
