//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// Copyright (c) Matthieu MEZIL.  All rights reserved.
// matthieu.mezil@live.fr

 
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using WCFAsyncQueryableServices.ClientContext.Interfaces;

namespace WAQSTest.ClientContext.Interfaces.Serialization
{
    [DataContract(Namespace="http://WAQSModel/SerializableContext")]
    public partial class WAQSModelSerializableContext : ISerializableContext
    {
        [DataMember]
        public List<WAQSTest.Entity1> Entity1 { get; set; }
    
    }
}
