//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// Copyright (c) Matthieu MEZIL.  All rights reserved.
// matthieu.mezil@live.fr

 
using System;
using System.Runtime.Serialization;

namespace WCFAsyncQueryableServices.ClientContext.Interfaces.Errors
{
    [DataContract(Namespace = "http://WCFAsyncQueryableServices/Errors")]
    public partial class ErrorDetail
    {
        [DataMember]
        public Guid EntityKey { get; set; }
        [DataMember]
        public string PropertyName { get; set; }
    }
}
